(function() {
  const noteData = JSON.parse(sessionStorage.getItem("noteContext") || "{}");
  const { id, name, fullLevel } = noteData;

  if (!id) {
    navigate("attendance");
    return;
  }

  document.getElementById("noteTitle").textContent = `Notes for ${name}`;
  document.getElementById("noteLevel").textContent = fullLevel || "Unknown Level";

  const container = document.getElementById("checklistContainer");
  const skills = (fullLevel && (SKILLS[fullLevel] || SKILLS[fullLevel.toUpperCase()])) || [];

  if (skills.length === 0) {
    container.innerHTML = "<p>No skills found for this level.</p>";
  } else {
    let html = `
      <div class="checklist-section">
        <div class="checklist-header">Skills Checklist</div>
    `;

    skills.forEach((skill, index) => {
      html += `
        <div class="skill-item">
          <span class="skill-label">${skill}</span>
          <div class="skill-controls">
            <div class="checkbox-wrapper">
              <label class="checkbox-label">Worked</label>
              <input type="checkbox" data-skill="${skill}" class="worked-on">
            </div>
            <div class="checkbox-wrapper">
              <label class="checkbox-label">Next</label>
              <input type="checkbox" data-skill="${skill}" class="next-time">
            </div>
          </div>
        </div>
      `;
    });
    html += "</div>";
    container.innerHTML = html;
  }

  document.getElementById("openPike13").addEventListener("click", () => {
    window.location.href = `https://mcdonaldswimschool.pike13.com/people/${id}/notes`;
  });

  document.getElementById("submitNote").addEventListener("click", async () => {
    const workedOn = [];
    const nextTime = [];

    container.querySelectorAll(".worked-on:checked").forEach(cb => {
      workedOn.push(cb.dataset.skill);
    });
    container.querySelectorAll(".next-time:checked").forEach(cb => {
      nextTime.push(cb.dataset.skill);
    });

    if (workedOn.length === 0 && nextTime.length === 0) {
      alert("Please select at least one skill.");
      return;
    }

    let noteBody = "";
    if (workedOn.length > 0) {
      noteBody += "Worked on:\n- " + workedOn.join("\n- ") + "\n\n";
    }
    if (nextTime.length > 0) {
      noteBody += "Next time:\n- " + nextTime.join("\n- ");
    }

    const submitBtn = document.getElementById("submitNote");
    submitBtn.disabled = true;
    submitBtn.textContent = "Submitting...";

    try {
      const response = await fetch(`https://mcdonaldswimschool.pike13.com/api/v2/desk/people/${id}/notes`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${localStorage.getItem("access_key")}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          note: {
            note: noteBody,
            public: true
          }
        })
      });

      if (response.ok) {
        alert("Note submitted successfully!");
        navigate("attendance");
      } else {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }
    } catch (error) {
      console.error("Error submitting note:", error);
      alert("Failed to submit note. Please try again.");
      submitBtn.disabled = false;
      submitBtn.textContent = "Submit";
    }
  });

  // Auto-populate logic (Back burner)
  // Attempt to fetch previous notes and pre-fill "Worked on" based on previous "Next time"
  (async () => {
      try {
        const response = await fetch(`https://mcdonaldswimschool.pike13.com/api/v2/desk/people/${id}/notes`, {
            method: "GET",
            headers: {
              "Authorization": `Bearer ${localStorage.getItem("access_key")}`,
              "Content-Type": "application/json"
            }
        });
        if (!response.ok) return;
        const data = await response.json();
        const notes = data.notes || [];
        // Find the most recent note that looks like it was generated by us (contains "Next time:")
        const lastChecklistNote = notes.find(n => n.note && n.note.includes("Next time:"));

        if (lastChecklistNote) {
            const nextTimeSection = lastChecklistNote.note.split("Next time:")[1];
            if (nextTimeSection) {
                const lines = nextTimeSection.split("\n").map(l => l.trim()).filter(l => l.startsWith("- "));
                const previousNextSkills = lines.map(l => l.substring(2));

                // Pre-fill 'Worked on' with these skills? Or just highlight them?
                // The user said "auto populate the persons not with the previous checklist submitted".
                // I will pre-check "Worked on" for items that were in "Next time" of previous note.
                // This assumes "Next time" means "We should work on this next time", so "Today" we worked on it.

                previousNextSkills.forEach(skill => {
                    const cb = container.querySelector(`.worked-on[data-skill="${skill}"]`);
                    if (cb) cb.checked = true;
                });
            }
        }
      } catch (e) {
          console.error("Error fetching previous notes", e);
      }
  })();

})();
